language: python
sudo: false
cache: pip

python:
  - "2.7"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
#      - libxml2-dev
#      - libxmlsec1-dev
#      - libxslt-dev

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - WKHTMLTOPDF_VERSION="0.12.4"
  - secure: ArnbVaF5+ry6zVysZ7HA9xcnQrodo8FsXXcon9yINTYRfDC9QEr+/mTLAPRl+lVLdtWV2GuGuX0vPYzBxFWpY3LR0BpKqXzx0G51s94zR2WWEmizYFzFhpAuIxoU4CYNckHFSUaPAQJhwB/pYx9+H/W6bMjG/VnZBq+AmBJ2Kh0=

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - TRANSIFEX="0"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install -r requirements.txt

before_script:
  - chmod +x configure_locale.sh

script:
  - sudo ./configure_locale.sh
  - travis_run_tests

after_success:
  - travis_after_tests_success