language: python

python:
  - "2.7"

cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - libxmlsec1-dev
      - poppler-utils

env:
  - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install reportlab
  - pip install unidecode
  - pip install suds
  - pip install signxml
  - pip install qrcode
  - pip install py3o.template
  - pip install sh
  - pip install https://github.com/odoo-brazil/pyxmlsec/archive/master.zip
  - pip install https://github.com/odoo-brazil/geraldo/archive/master.zip
  - pip install https://github.com/aricaldeira/PySPED/archive/master.zip#egg=PySPED-1.1.0 --allow-external PyXMLSec --allow-insecure PyXMLSec

before_script:
  - chmod +x configure_locale.sh

script:
  - sudo ./configure_locale.sh
  - travis_run_tests

after_success:
  coveralls
