language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "3.6"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - libxml2-dev
      - libxmlsec1-dev
      - libxslt-dev
      - swig

stages:
  - linting
  - test

jobs:
  include:
    - stage: linting
      name: "pre-commit"
      python: "3.6"
      before_install:
      install: pip install pre-commit
      script: pre-commit run --all --show-diff-on-failure --verbose --color always
      after_success:
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1" EXCLUDE="payment_pagseguro,l10n_br_website_sale_delivery,l10n_br_website_sale"
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="payment_pagseguro,l10n_br_website_sale_delivery,l10n_br_website_sale"

env:
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1" EXCLUDE="payment_pagseguro,l10n_br_website_sale_delivery,l10n_br_website_sale"
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="payment_pagseguro,l10n_br_website_sale_delivery,l10n_br_website_sale"


install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git
    ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - export WKHTMLTOPDF_VERSION=0.12.5
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
